export const login = {
  page: "min-h-screen flex flex-col items-center justify-center relative overflow-hidden p-5",
  glow: "absolute top-[12%] left-1/2 -translate-x-1/2 w-[600px] h-[450px] pointer-events-none",
  book: "relative flex rounded [perspective:1200px] [transform-style:preserve-3d] z-[1]",
  pageL: "w-[260px] min-h-[340px] rounded-l p-[18px_22px_22px] relative flex flex-col overflow-hidden",
  pageR: "w-[260px] min-h-[340px] rounded-r p-[18px_22px_22px] relative flex flex-col overflow-hidden",
  spine: "w-5 flex flex-col items-center justify-evenly py-[25px]",
  spineDec: "w-2.5 h-0.5 rounded",
  orn: "text-center mb-1",
  ornCh: "text-sm text-[#c9a96e] tracking-[6px]",
  title: "font-book text-[28px] font-bold text-[#2c1810] text-center mb-0.5 tracking-wide",
  sub: "font-book text-[13px] font-light italic text-[#6b5a48] text-center mb-2",
  hr: "w-[55%] h-px mx-auto mb-4 border-none",
  fg: "mb-3.5 flex-1 relative z-10",
  label: "font-book block text-xs font-semibold text-[#4a3828] mb-1.5 tracking-[0.5px] uppercase",
  input: "font-hand w-full px-3.5 py-2 text-[22px] font-semibold text-[#1a1a3e] bg-transparent border-none outline-none box-border",
  pn: "font-book absolute bottom-2.5 right-4 text-[11px] italic text-[#a89880]",
  btn: "font-book inline-flex items-center justify-center w-full h-11 mt-1 text-[#f4e8d1] rounded-b-md text-[15px] font-bold tracking-[1.5px] cursor-pointer z-[2] uppercase px-6",
  err: "font-book text-[13px] text-[#8b1a1a] mt-3 italic text-center z-[2]",
  quill: "absolute pointer-events-none",
  dot: "absolute w-[5px] h-[5px] rounded-full pointer-events-none z-[25]",
  watch: "absolute z-[35] pointer-events-none flex flex-col items-center",
  watchTxt: "font-book mt-2 text-[14px] italic text-[#c9a96e] tracking-[2px] opacity-80",
  tear: "absolute inset-0 overflow-hidden pointer-events-none z-[15]",
  tearLine: "absolute top-[-10%] left-[25%] w-1 h-[120%] -rotate-12 origin-center",
  glow2: "absolute inset-[-20%] pointer-events-none z-10",
  dim: "absolute inset-0 pointer-events-none z-[3]",
};